development:
  adapter: postgresql
  database: profcyn_development
  username: paul
  password: 
  encoding: utf8
  
test:
  adapter: postgresql
  database: profcyn_test
  username: paul
  password: 
  encoding: utf8
  
production:
  adapter: postgresql
  database: profcyn_production
  username: paul
  password: 
  encoding: utf8
