development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: profcyn-gallery_development

test: &test
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: profcyn-gallery_test

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: profcyn-gallery_production
